apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wuda-app.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "wuda-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: frontend

spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wuda-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: frontend

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wuda-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: frontend

    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.frontend.containerPort }}

          env:
            - name: BACKEND_HOSTNAME
              value: {{ .Values.frontend.env.BACKEND_HOSTNAME }}
            - name: BACKEND_PORT
              value: "{{ .Values.frontend.env.BACKEND_PORT }}"
            - name: SECRET_KEY
              value: {{ .Values.frontend.env.SECRET_KEY }}
            - name: APP_HOST
              value: {{ .Values.frontend.env.APP_HOST }}
            - name: APP_PORT
              value: "{{ .Values.frontend.env.APP_PORT }}"

          {{- if .Values.frontend.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelay }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}
          {{- end }}

          {{- if .Values.frontend.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelay }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold }}
          {{- end }}
